entity: "whysax-agnetic-labs"
project: "MazeSFT"
name: "Initial"

model:
  name: "tiny_man"
  vocab_size: 10
  output_vocab_size: 5
  d_model: 32
  n_layers: 3
  max_seq_len: 64
  n_heads: 1
  dropout: 0
  batch_size: 32
  num_epochs: 150
  learning_rate: 0.0001
  device: mps
  output_dir: models/

dataset:
  small:
    size: 4
    num_train: 256
    num_test: 32
  tiny:
    size: 2
    num_train: 32
    num_test: 8
  output_dir: data
