entity: "whysax-agnetic-labs"
project: "MazeSFT"
name: "small_mazes"

model:
  name: "grpo_1"
  vocab_size: 10
  output_vocab_size: 5
  d_model: 64
  n_layers: 5
  max_seq_len: 32
  n_heads: 4
  dropout: 0
  device: cuda

training:
  grpo:
    batch_size: 64
    group_size: 16
    kl_penalty: 0.001
    eps: 0.2
    sampling_temperature: 2
    learning_rate: 0.00005
    num_epochs: 100
    baseline_update_frequency: 1
    output_dir: models/
    device: cuda


dataset:
  grpo:
    four:
      size: 4
      num_train: 512
      num_test: 256
    three:
      size: 3
      num_train: 256
      num_test: 128
    output_dir: grpo_data
